
<section class="contact" id="contact">
    <h1 class="heading"><span>contact</span>us</h1>
    
    <div class="row">
      <iframe class="map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3419.3600918434795!2d31.378677299999985!3d31.01621560000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14f79c473b2055b1%3A0xe683c9e51dbbf6a4!2sMisr%20higher%20institute%20for%20engineering%20and%20technology!5e0!3m2!1sen!2seg!4v1715487417869!5m2!1sen!2seg"  allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
      <form action="">
        <h3>contact us</h3>
        <div class="inputbox">
            <span class="fas fa-user"></span>
            <input type="text" placeholder="name">
        </div>

        <div class="inputbox">
            <span class="fas fa-envelope"></span>
            <input type="email" placeholder="email">
        </div>
        <div class="inputbox">
            <span class="fas fa-phone"></span>
            <input type="number" placeholder="number">
        </div>
        <input type="submit" value="contact now" class="btn">
      </form>
    </div>
  </section>





  
.home-hero .cta-btn {
  display: inline-block;
  padding: 1rem 2rem;
  background: linear-gradient(45deg,var(--bu),var(--gd));
  color:var(--wh);
  font-weight: 700;
  border: none;
  border-radius: 50px;
  font-size: 2.2rem;
  text-decoration: none;
  box-shadow: 0 0 20px #FFD700;
  transition: all 0.3s;
  margin: 4rem;
  position: relative;
  z-index: 3; /* مهم عشان يكون فوق كل الخلفيات */
 

}

.home-hero .cta-btn:hover {
  box-shadow: 0 0 40px var(--gd);
  transform: translateY(-3px);
}